### ISSUE TITLE
doesn't compile on kubuntu 17.10

### ISSUE THREAD

**Issue by altagir** [innovacoin/innova#9]
Incompatible libboost-system-dev on my system (1.62.0.1)
some other coins bundle it inside the project and provide a build script 
I never been able to solve this issue when compiling

```
 % make
Making all in src
  CXXLD    innovad
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option)':
/data/usr/local/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&)':
/data/usr/local/include/boost/filesystem/operations.hpp:384: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function `boost::this_thread::sleep_for(boost::chrono::duration<long long, boost::ratio<1ll, 1000000000ll> > const&)':
/data/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
```
